### ISSUE TITLE
adding groups when importing

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/rest-on-couch#123]
For NMR I have a filter like
```
    getOwner: async function getOwner(filename) {
        const username = parseFilename(filename).username;
        const userInfo = await config.getUserInfo(username);
        return userInfo.email;
    },
    getGroups: async function getGroups(filename) {
        const userInfo = await config.getUserInfo(username);
        return userInfo.allGroups;
    },
```

While getOwner is called it seems that getGroups is never used. Before I was directly changing the result in this case but now I'm a little bit blocked.

**Comment by lpatiny** [comment]
There is a planned way today that allows to return an array of owners when asked for `getOwner` but I still think that `getGroups` would be more intuitive or `getOwners`. Seems strange to return an array when it is singular.
Here is the way that works today
```
    getOwner: async function getOwner(filename) {
        const username = parseFilename(filename).username;
        const userInfo = await config.getUserInfo(username);
        let owners=[userInfo.email];
        if (userInfo.allGroups && userInfo.allGroups.length>0) {
                owners=owners.concat(userInfo.allGroups);
        }
        return owners;
    },
```

**Comment by targos** [comment]
You should use the new way to write import scripts that works with a single function. This is deprecated.
