### ISSUE TITLE
allow to set the property result.filename

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/rest-on-couch#130]
In order to change the filename during importation

**Comment by stropitek** [comment]
Changing the filename should be done by using `result.skipAttachment` and using the `result.addAttachment` instead. This should be documented though.

**Comment by targos** [comment]
Seems to me that everything that can be done with addAttachment should be possible with the file being imported

**Comment by targos** [comment]
Fixed in https://github.com/cheminfo/rest-on-couch/pull/146

@stropitek don't forget to add `Fixes: URL` to the commit message for automatic closing ;)
