### ISSUE TITLE
Importation of unknown extension and error message

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/rest-on-couch#134]
I have an importation procedure that checks for extensions and only allow .jdx or .dx extension.

When I try to import a '.fid' file I'm throwing an error
```
  if (!ctx.filename.match(/\.(jdx|dx)$/i)) {
    throw new Error('NMR importation unexpected file extension: ' + filename);
  }
```

However in the log I received the information `rest-on-couch: filename is not defined` instead of my message. What am I doing wrong ?

**Comment by stropitek** [comment]
You will be facepalming :man_facepalming: 
`... + filename` -> `... + ctx.filename`
