### ISSUE TITLE
couchdb connection error

### ISSUE THREAD

**Issue by stropitek** [cheminfo/rest-on-couch#140]
I recently came across an error while using a view (ecstasy pill view).

It was making quiet a lot of requests to get images in parallel from rest-on-couch.

The issue can be reproduced from here, when logged in as admin@cheminfo.org:
https://my.cheminfo.org/?v=v2.68.0&viewURL=https%3A%2F%2Fmydb.cheminfo.org%2Fdb%2Fvisualizer%2Fentry%2Fa1b8a96196811ddc29691f54bcbd59db%2Fview.json%3Frev%3D5-9d71fcac8f28c349ad939b85e4d9a0cc

Logs:
```
1|rest-on- | 2018-08-24T08:29:05.031Z couch:debug (main:attachment) getAttachmentByName (ef1472ec1a5c37c5fa76d46686e1f31a, image/data/0140_1_extracted.png, admin@cheminfo.org)
1|rest-on- | 2018-08-24T08:29:05.031Z couch:debug (main:entry) getEntryWithRights (ef1472ec1a5c37c5fa76d46686e1f31a, admin@cheminfo.org, read)
1|rest-on- | 2018-08-24T08:29:05.032Z couch:warn (nano) getDocument failed
1|rest-on- | 2018-08-24T08:29:05.033Z couch:error (middleware:util) Error: error happened in your connectionError: socket hang up
1|rest-on- |     at createHangUpError (_http_client.js:313:15)
1|rest-on- |     at Socket.socketCloseListener (_http_client.js:354:25)
1|rest-on- |     at Socket.emit (events.js:187:15)
1|rest-on- |     at Socket.EventEmitter.emit (domain.js:442:20)
1|rest-on- |     at TCP._handle.close (net.js:595:12)

```

**Comment by stropitek** [comment]
Changing https://github.com/cheminfo/rest-on-couch/blob/a5eadacf5cbd742b928e7b2097488bbdaa51eef2/src/connect.js#L12 to allow a pool of 200 sockets instead of 50, I don't get the error.

The view is making about 190 image requests

**Comment by targos** [comment]
How is it able to do so many requests in parallel? I thought the browser had a limit.
Anyway, that's an issue because if many clients are requesting attachments at the same time we could still have this problem.

**Comment by targos** [comment]
Can we set it to `Infinity`?

**Comment by stropitek** [comment]
We added this to solve another problem, we should see what it was. But yes I would instead use `keepAlive: true` and `maxFreeSocket` instead (just to avoid leaks if many sockets open at some point)

**Comment by stropitek** [comment]
https://github.com/apache/nano#pool-size-and-open-sockets
