### ISSUE TITLE
Give the possibility to get the last stored revision ID for a document

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/rest-on-couch#143]
Using HEAD it is possible to get from a document UUID the last revision (Etag).

Having a way to retrieve this using a setInterval would allow to warn the user that his displayed version is not up-to-date anymore.

It could also tell the user that he is not connected to the system anymore if this query fails.

http://docs.couchdb.org/en/stable/api/document/common.html

**Comment by targos** [comment]
We can't use this API to verify if the user has access to the document.
However, we can create a similar one. Just need a new view that emits _id and _rev with owner.
