### ISSUE TITLE
import's addAttachment should not allow non-base64 contents

### ISSUE THREAD

**Issue by targos** [cheminfo/rest-on-couch#158]

**Comment by targos** [comment]
When a Buffer is passed, it is automatically converted to base64.
When a string is passed, it is just forwarded to CouchDB and the upload fails if it isn't valid base64.

**Comment by targos** [comment]
@stropitek 
what do you think we should do?
- validate that strings are basa64-encoded?
- assume they are not and always convert?
- other?

**Comment by stropitek** [comment]
I would not always convert. I prefer to have an error than saving something that is not what I intended to save. We can keep the behavior as it is. The goal of validating would be to have a more explicit error than the one returned by couchDB?

**Comment by targos** [comment]
The current problem is that the entry is in a middle state. It was created but then attachment failed to be uploaded. Validating would prevent that and allow for a more explicit error.

> I prefer to have an error than saving something that is not what I intended to save.

What do you mean? If it's converted automatically, you don't get an error AND you save what you intended to save.

**Comment by targos** [comment]
another possibility is to force a Buffer and user has to do `Buffer.from(string, 'base64' | 'utf8')`

**Comment by targos** [comment]
that might actually be the best approach because there is no ambiguity and we don't need to do a costly validation

**Comment by stropitek** [comment]
ok, I like the Buffer only solution

**Comment by targos** [comment]
working on it
