### ISSUE TITLE
showing group memberships fails

### ISSUE THREAD

**Issue by stropitek** [cheminfo/rest-on-couch#169]
version: 6.0.0

https://mydb.cheminfo.org/#/group_memberships

![image](https://user-images.githubusercontent.com/4118690/47790884-972c0c00-dd18-11e8-9977-789b7fefeb61.png)

**Comment by targos** [comment]
We should give this UI some love. It's been a long time.

**Comment by stropitek** [comment]
The problem only happens if no database is selected. The menu should not show up if no database is selected.

**Comment by targos** [comment]
I can't reproduce in a dev environment. Will try again on mydb after https://github.com/cheminfo/rest-on-couch/pull/172 is merged

**Comment by targos** [comment]
OK, got it. I had `autoCreateDatabase` set to true in dev
