### ISSUE TITLE
adding a right to a group causes the page to crash

### ISSUE THREAD

**Issue by stropitek** [cheminfo/rest-on-couch#186]
I can produce this error on mydb.cheminfo.org

The group rights are successfully modified, but the page crashes.

We should try to reproduce in dev to get a usable react error

![image](https://user-images.githubusercontent.com/4118690/48731476-66673480-ec3d-11e8-9262-61bc5366718d.png)

**Comment by targos** [comment]
Is it a new bug?

**Comment by stropitek** [comment]
don't think I have seen it before, but could be not so recent, since I'm not using the interface to add rights very often.
