### ISSUE TITLE
Possible bug in url encoding

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/rest-on-couch#201]
Some of my attachment names contain a '+' (I know it is a bad idea).

One of the problem is that the httpd proxy will unescape the URL before forwarding it to Roc.

This can be solved by changing the conf file and have something like:
```
        AllowEncodedSlashes NoDecode

        ProxyPass / http://localhost:4444/ nocanon
        ProxyPassReverse / http://localhost:4444/
```

After leaving the httpd proxy the query goes to Roc and I guess that Roc receives something like: 

https://mydb.cheminfo.org/db/eln/entry/5c412ce29e99de1fd8935fb7f0b2e836/spectra/ir/test%2Bplus.JDX

But if I check the log of couchdb the query received is

https://mydb.cheminfo.org/db/eln/entry/5c412ce29e99de1fd8935fb7f0b2e836/spectra/ir/test+plus.JDX

And the result is file not found.

Could you check if Roc is indeed unescaping the URI ?

**Comment by targos** [comment]
it's not that Roc is unescaping the URI, it receives it unescaped and has to escape it again.
Fix in https://github.com/cheminfo/rest-on-couch/pull/202

**Comment by lpatiny** [comment]
Thanks !

**Comment by targos** [comment]
the fix is now deployed on c6h6 if you want to test it
