### ISSUE TITLE
Retrieve the revision

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/rest-on-couch#203]
It should be possible to make this kind of query:

```
let url='https://mydb.cheminfo.org/db/eln/entry/b8d44e7857fac800ae119b7671a9c9f3';

let result=await fetch(url, {
	method: 'HEAD',
    mode: 'cors',
    credentials: 'include',
});
console.log(result.headers);
```
When in all the cases the result.headers is empty while in the network console the ETag containing the revision is correctly return.

It could be related to CORS and I also tried to add on the server the following line:
```
Header set Access-Control-Allow-Headers "ETag, Content-Type, Access-Control-Allow-Headers, Authorization, X-Requested-With"
```

In all my trials the `result.headers`is an empty object.

Any idea what I'm doing wrong ?

The goal here is to implement a monitoring system to warn the end-users when there is a new revision on the server.

**Comment by targos** [comment]
This query is not possible in roc and wouldn't be much more efficient than a normal GET because we need to do a full query for permissions

**Comment by lpatiny** [comment]
In the API documentation there is:

```
HEAD | /db/:dbname/entry/:uuid | Get HTTP headers about the document | Similar to HEAD /:dbname/:docid in CouchDB
```
And if I check the network connection in the browser I really retrieve my ETag (revision of couchdb). It is just that from javascript I never could retrieve the header field.

Do you think there should be an new url like:
```
/db/:dbname/entry/:uuid/_rev
```
to retrieve revision ?

**Comment by targos** [comment]
Please read the documentation of fetch. The headers object is not what you think. I confirm `result.headers.get('etag')` returns the expected value
