### ISSUE TITLE
Define an array of importation path

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/rest-on-couch#25]
In the case of NMR we have sometimes 10 machines that are mounted on a linux server.

```
/mnt/spectro1/jcamp/
/mnt/spectro2/jcamp/
/mnt/spectro3/jcamp/
/mnt/spectro4/jcamp/
/mnt/spectro5/jcamp/
```
We should be able to define an array of folders that has to be checked and in each of those folders move the file to the corresponding "processed" folder.
Also because it is mounted folder linux is not aware when a file changes. There should be an option that the importation process is run continuously with a specified sleep time before 2 checks. For example it could import all the files in all the folder, sleep one minute and do the process again and again.

**Comment by targos** [comment]
where should be the processed folder ?
