### ISSUE TITLE
Import data from UUID

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/rest-on-couch#291]
I need to import some experiments for which the only information I have is the 12 first characters of the uuid of the couchDB entry. I have no idea about the owner but obviously the data is already in the database.

Practically the lab prints labels on their sample and would like to go to an instrument, scan the label as filename and do their experiment.

If I know the username I can use:

```js
let results = await ctx.couch.queryEntriesByUser(
  userInfo.email,
  'sampleByUuid',
  {
    startkey: [userInfo.email, info.uuid],
    endkey: [userInfo.email, info.uuid + '\uffff'],
    limit: 2
  }
);
```

Because I don't know the username I though about adding a `superAdministrator` (import@cheminfo.org) that should be allowed in the importation script to read any entry using something like:

https://github.com/cheminfo/rest-on-couch/blob/9e24609226090665deaa04175d52ae49fec20159/src/couch/entry.js#L13-L17

But this method requires to know the full UUID.

So is there another approach ? Otherwise I would make a PR to add a new method `getEntryByBeginningUUID`

@targos @stropitek any advice ?

**Comment by targos** [comment]
Could you not add a new CouchDB view/index to your app that emits the first characters of the uuid?

**Comment by stropitek** [comment]
I think you could duplicate `sampleWithUuid` in another view that does not set the "view with owner" flag, and then call `couch.queryViewByUser` instead of `couch.queryEntriesByUser`. A super administrator should be able to see all the results that match the query.

**Comment by stropitek** [comment]
Sorry, `queryEntriesByUser` is very similar to `queryViewByUser` actually

Why can't you use `queryEntriesByUser` with your super-administrator email?

**Comment by stropitek** [comment]
From my current understanding `queryEntriesByUser` should work if you pass a super administrator as an email, weather the view has `withOwner` set or not. If you want to check if there is more than one result for this uuid start, it's easier to have a view that does not emit each document multiple times.

Do you have a couch setup with random uuid? The "starts with" approach would not work with the default uuid

**Comment by lpatiny** [comment]
Thanks for your help !

I create a view (uuid12) containing the 12 first characters

```js
function (doc) {
    if (doc.$type !== 'entry') return;
    emit(doc._id.substring(0,12));
  }
```

I added a super-administrator

`superAdministrators: ['import@cheminfo.org'], // super administrators have rights to all the sample`

And I have a test file

```
const Couch = require('../rest-on-couch-source/src');

const config = require('./config');

const couch = new Couch('eln');

const id = '546ec20564ae';
doAll();

async function doAll() {
  let results = await couch.queryEntriesByUser('import@cheminfo.org', 'uuid12', {
    key: id,
    reduce: false,
    include_docs: false,
  });

  console.log(results);
}
```

working now on the importation script

**Comment by stropitek** [comment]
FYI, you can also give import@cheminfo.org global owner rights, that would also work instead of making them a super admin
