### ISSUE TITLE
how to sort result of a view ?

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/rest-on-couch#33]
I would like to retrieve the TOC of the sample sorted by decreasing modification date. Is this possible ?

Currently I have something like:
``` 
        roc.query('sample_toc', {
            varName: 'samples'
        });
```

**Comment by targos** [comment]
did you try with `descending: true` ? in the same object of options

**Comment by targos** [comment]
but you need the TOC to emit the modification date as a key

**Comment by targos** [comment]
anyway I think it will work better if you sort it in the web page

**Comment by lpatiny** [comment]
@stropitek Maybe doView could accept a sort callback function and indeed we need to export $modificationDate as well to be able to sort. This could be the default behaviour in the Home page view to sort by decreasing modification date

**Comment by stropitek** [comment]
I've added the sort option in roc for queries and views, and use it in the Home page
