### ISSUE TITLE
Update Node.js support

### ISSUE THREAD

**Issue by targos** [cheminfo/rest-on-couch#339]
- [x] Remove v12
- [x] Switch to v16 in volta config and Dockerfile
- [x] Add v18 to test matrix

**Comment by stropitek** [comment]
- There seems to be an issue with v8-to-istanbul in node 18. https://github.com/cheminfo/rest-on-couch/runs/6092945510?check_suite_focus=true
- Deps cannot be installed with node16 because of outdated react peer dep in react-select2-wrapper

**Comment by targos** [comment]
> Deps cannot be installed with node16 

I don't see that in the PR ?

**Comment by targos** [comment]
v8-to-istanbul is fixed, but in a major release: https://github.com/istanbuljs/v8-to-istanbul/releases/tag/v9.0.0

What is our dependency that needs to upgrade?

**Comment by targos** [comment]
I think it's Jest? We can try with the latest alpha of v28: https://github.com/facebook/jest/releases/tag/v28.0.0-alpha.11

**Comment by stropitek** [comment]
> I don't see that in the PR ?

I have the issue locally when `rm -rf package-lock.json node_modules && npm i`

**Comment by targos** [comment]
You can run it with `--force` to bypass the error.

**Comment by stropitek** [comment]
should be able to be able to add node18 support after next jest upgrade

https://github.com/cheminfo/rest-on-couch/pull/340#issuecomment-1103796482
