### ISSUE TITLE
sample.cheminfo.org and conflict

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/rest-on-couch#34]
The home page now makes one query per line and this yields to 'conflict'.

The reason is quite simple. We display the modificationDate and therefore it needs to load all the documents.
However this conflict story is still annoying and shoud be fixed I think.

After in the view sample_toc we should emit the modificationDate and I wonder if we need to keep 2 copies of the ID (currently it is in the value and at the first level).

**Comment by targos** [comment]
what is causing the conflict L

**Comment by lpatiny** [comment]
Opening sample.cheminfo.org and refresh couple of time will cause the message 'conflict'. Don't know what is causing it. There is no error in console.

**Comment by stropitek** [comment]
I've had the problem but I'm no longer able to reproduce
