### ISSUE TITLE
sample.cheminfo.org and loading product

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/rest-on-couch#35]
The products are not loaded on load and you need to refresh to get the list.

There is also in the 'select' the empty value and I'm not sure this value is required. By default it should remember maybe the last group ?

**Comment by stropitek** [comment]
The empty value is not set by me. It's added by onde, don't know why

**Comment by stropitek** [comment]
https://github.com/NPellet/visualizer/issues/948
