### ISSUE TITLE
Getting command line error

### ISSUE THREAD

**Issue by chaitanya9186** [cheminfo/rest-on-couch#42]
I am getting following error while running _rest-on-couch sever --help_

-bash: /FOLDER/.nvm/versions/node/v6.0.0/bin/rest-on-couch: /bin/env: bad interpreter: No such file or directory

OS: OS X El Capitan 10.11.6

Thank you

**Comment by stropitek** [comment]
I changed the interpreter and it should solve your problem. Let us know if not.
Thanks for the feedback!

**Comment by targos** [comment]
I actually removed the global install support in a recent commit and am working on npm scripts to start the services.
